version: '3.7'

# Settings and configurations that are common for all containers
x-minio-common: &minio-common
  image: minio/minio:RELEASE.2021-07-22T05-23-32Z
  command: server --console-address ":9001" /data
  expose:
    - "9000"
    - "9001"
  environment:
    MINIO_ROOT_USER: ${MINIO_ROOT_USER}
    MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD}
  healthcheck:
    test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
    interval: 30s
    timeout: 20s
    retries: 3
  networks:
    - minio

services:
  minio1:
    <<: *minio-common
    hostname: minio1
    volumes:
      - ./minio/data/:/data
      - ./minio/conf/:/root/.minio

  #nginx:
  #  image: nginx:1.19.2-alpine
  #  hostname: nginx
  #  volumes:
  #    - ./nginx.conf:/etc/nginx/nginx.conf:ro
  #  ports:
  #    - "9000:9000"
  #    - "9001:9001"
  #  depends_on:
  #    - minio1
networks:
  minio:
