version: '3.7'

services:
  minio1:
    image: minio/minio:RELEASE.2021-06-17T00-10-46Z
    hostname: minio1
    volumes:
      - ./minio/data/:/data
      - ./minio/conf/:/root/.minio
    expose:
      - "9000"
    environment:
      MINIO_ROOT_USER: ${MINIO_ROOT_USER}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD}
    command: server /data
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 30s
      timeout: 20s
      retries: 3

  nginx:
    image: nginx:1.19.2-alpine
    hostname: nginx
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - "9001:9000"
    depends_on:
      - minio1
